version: '3'

services:

    client:
        build: './public'
        image: chatappreg.azurecr.io/client
        ports:
            - "3000:3000"

    server:
        build: './server'
        image: chatappreg.azurecr.io/server
        ports:
            - "5002:5002"

    db:
        build: './db'
        image: chatappreg.azurecr.io/db
        ports:
            - "5003:5003"